/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as PagesRouteRouteImport } from './routes/_pages/route'
import { Route as PagesIndexRouteImport } from './routes/_pages/index'
import { Route as PagesSolutionsRouteImport } from './routes/_pages/solutions'
import { Route as PagesLegalRouteImport } from './routes/_pages/legal'
import { Route as PagesFeaturesRouteImport } from './routes/_pages/features'
import { Route as PagesFaqRouteImport } from './routes/_pages/faq'
import { Route as PagesContactRouteImport } from './routes/_pages/contact'
import { Route as PagesAboutRouteImport } from './routes/_pages/about'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRouteRoute = PagesRouteRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesSolutionsRoute = PagesSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesLegalRoute = PagesLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesFeaturesRoute = PagesFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesFaqRoute = PagesFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesContactRoute = PagesContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PagesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PagesIndexRoute
  '/waitlist': typeof WaitlistRoute
  '/about': typeof PagesAboutRoute
  '/contact': typeof PagesContactRoute
  '/faq': typeof PagesFaqRoute
  '/features': typeof PagesFeaturesRoute
  '/legal': typeof PagesLegalRoute
  '/solutions': typeof PagesSolutionsRoute
}
export interface FileRoutesByTo {
  '/waitlist': typeof WaitlistRoute
  '/about': typeof PagesAboutRoute
  '/contact': typeof PagesContactRoute
  '/faq': typeof PagesFaqRoute
  '/features': typeof PagesFeaturesRoute
  '/legal': typeof PagesLegalRoute
  '/solutions': typeof PagesSolutionsRoute
  '/': typeof PagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pages': typeof PagesRouteRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/_pages/about': typeof PagesAboutRoute
  '/_pages/contact': typeof PagesContactRoute
  '/_pages/faq': typeof PagesFaqRoute
  '/_pages/features': typeof PagesFeaturesRoute
  '/_pages/legal': typeof PagesLegalRoute
  '/_pages/solutions': typeof PagesSolutionsRoute
  '/_pages/': typeof PagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/waitlist'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/legal'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/waitlist'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/legal'
    | '/solutions'
    | '/'
  id:
    | '__root__'
    | '/_pages'
    | '/waitlist'
    | '/_pages/about'
    | '/_pages/contact'
    | '/_pages/faq'
    | '/_pages/features'
    | '/_pages/legal'
    | '/_pages/solutions'
    | '/_pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PagesRouteRoute: typeof PagesRouteRouteWithChildren
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/': {
      id: '/_pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/solutions': {
      id: '/_pages/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof PagesSolutionsRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/legal': {
      id: '/_pages/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof PagesLegalRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/features': {
      id: '/_pages/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof PagesFeaturesRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/faq': {
      id: '/_pages/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PagesFaqRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/contact': {
      id: '/_pages/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PagesContactRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/about': {
      id: '/_pages/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof PagesRouteRoute
    }
  }
}

interface PagesRouteRouteChildren {
  PagesAboutRoute: typeof PagesAboutRoute
  PagesContactRoute: typeof PagesContactRoute
  PagesFaqRoute: typeof PagesFaqRoute
  PagesFeaturesRoute: typeof PagesFeaturesRoute
  PagesLegalRoute: typeof PagesLegalRoute
  PagesSolutionsRoute: typeof PagesSolutionsRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

const PagesRouteRouteChildren: PagesRouteRouteChildren = {
  PagesAboutRoute: PagesAboutRoute,
  PagesContactRoute: PagesContactRoute,
  PagesFaqRoute: PagesFaqRoute,
  PagesFeaturesRoute: PagesFeaturesRoute,
  PagesLegalRoute: PagesLegalRoute,
  PagesSolutionsRoute: PagesSolutionsRoute,
  PagesIndexRoute: PagesIndexRoute,
}

const PagesRouteRouteWithChildren = PagesRouteRoute._addFileChildren(
  PagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PagesRouteRoute: PagesRouteRouteWithChildren,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
